[tool.black]
line-length = 90
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
)/
'''

[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja"]
